AUDIO_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no
RGBLIGHT_SUPPORTED = no

DEBUG_ENABLE = no

SERIAL_DRIVER = vendor

POINTING_DEVICE_DRIVER = cirque_pinnacle_spi

PICO_INTRINSICS_ENABLED = no # ATM Unsupported by ChibiOS.
