AUDIO_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no

OLED_DRIVER = ssd1306

OPT_DEFS += -DHAL_USE_I2C=TRUE

SERIAL_DRIVER = vendor

POINTING_DEVICE_DRIVER = cirque_pinnacle_spi

# RP2040-specific options
PICO_INTRINSICS_ENABLED = no # ATM Unsupported by ChibiOS.
